services:
  app:
    container_name: hillshade-wms
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./scratch:/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
