services:
  app:
    container_name: hillshade-wms
    platform: linux/amd64
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./scratch:/tmp